### PR TITLE
Clean server install resource

### PR DESCRIPTION
**Pull request by fernandoaleman**
# Description

Remove unused properties from server_install resource

Removed the following properties:

- mycnf_file
- extconf_directory
- data_directory
- external_pid_file
- port
- initdb_locale

Updated documentation to reflect the changes.

Fix default pid file for rhel, fedora and amazon

Updated default mariadb version to 10.11 in all tests

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [X] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by damacus** [comment]
Looks good! 

can you remove amalon-linux2 from the Ci matrix too, please?

**Comment by damacus** [comment]
@fernandoaleman I've rebased. Can you double check that makes sense please?

**Comment by fernandoaleman** [comment]
@damacus I added another commit defaulting mariadb to version 10.11 in all the testing and removing tests on version 10.3 and 10.4. However, I noticed that `client_install` tests are failing on Debian and Ubuntu. I'll take a look at those tomorrow and submit a fix when ready.

**Comment by fernandoaleman** [comment]
@damacus This PR keeps failing CI because of the `check-metadata` job, I'm guessing it's because it's from a fork. Would you like me to close this PR and re-submit from a `sous-chefs` branch instead of a fork?

**Comment by damacus** [comment]
If you could for now until I fix the logic I'm not sure which bit of the permissions is failing right now.

**Comment by fernandoaleman** [comment]
@damacus Closing this PR and re-opening PR #365 in order to get past the CI `check-metadata` failures.

**Pull request closed without merging**
