### PR TITLE
Fix for grants template and execution

### PR DESCRIPTION
**Pull request by jwmarshall**
This fixes the unary operator expected error in the grants script, as well as the execution block.

Fixes issue: https://github.com/sinfomicien/mariadb/issues/108

### CODE REVIEW

**Comment by goatherd** [comment]
@jwmarshall what does `bash -e` change exactly? Could not find this documented and only know about the `echo -e` behaviour. Is this related?

**Comment by jwmarshall** [comment]
`bash -e` causes a script to exit on the first error (non-zero exit code) it encounters. Unfortunately it does not actually catch the unary operator issue (nor would it exit) as it only catches error codes for commands executed in the script.

Nevertheless I believe it is the correct behaviour that this script should exit and throw a non-zero exit code if either of the two commands (one to look up the root user rows, the second to remove that user) should fail.

**Comment by jwmarshall** [comment]
Added a quick fix to the foodcritic complaint that was failing your CI tests.

**Comment by jwmarshall** [comment]
@sinfomicien @joerocklin

**Pull request merged**
