### PR TITLE
Fix replication provider and server_id

### PR DESCRIPTION
**Pull request by jwmarshall**
START SLAVE fails due to nil string when replication resource name is default.
Fix server_id key in replication config.

### CODE REVIEW

**Comment by jwmarshall** [comment]
Meant to PR this on my own branch to continue testing, but fix is probably relevant to anyone who wants to use the replication provider.

**Comment by aberrios85** [comment]
Just hit this one. Can we get this pulled?

**Comment by jwmarshall** [comment]
@aberrios85 you're welcome to use the master branch of my fork which has merged all three of the PR's I have pending with this cookbook.

**Comment by shoekstra** [comment]
Hi!

I'm in process of sorting out some integration tests for this cookbook - once those are done we can rebase and try get this merged!

**Comment by shoekstra** [comment]
Looks good! I've rebased this PR off master and it will be merged via #140 if all goes well.

**Comment by shoekstra** [comment]
Merged in #140 - thanks!

**Pull request closed without merging**
