### PR TITLE
Add support for configuring skip-name-resolve

### PR DESCRIPTION
**Pull request by JCotton1123**
@mjuszczak would you mind reviewing (and possibly merging)

### CODE REVIEW

**Comment by mjuszczak** [comment]
@JCotton1123 Has a kitchen test passed with this parameter enabled, successfully starting MySQL?

**Comment by JCotton1123** [comment]
I ran kitchen converge successfully but not kitchen test. The kitchen stuff seems to be partially broken. I had to modify .kitchen.yml to get converge to work.

**Comment by mjuszczak** [comment]
OK - and "show global variables like 'skip_name_resolve'" was ON?

**Comment by JCotton1123** [comment]
```
MariaDB [(none)]> show global variables like 'skip_name_resolve';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| skip_name_resolve | ON    |
+-------------------+-------+
```

**Comment by mjuszczak** [comment]
:shipit:

**Pull request merged**
