### PR TITLE
Change apt_repository property, because it conflicts with apt resource

### PR DESCRIPTION
**Pull request by sinfomicien**
## Description

It correct the repository install for Chef 13

### Issues Resolved

Resolve issue [#245]

### Check List
- [X] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [O] New functionality includes testing. (as it's mainly for chef 13 support, no tests added)
- [N/A] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by xorima — DISMISSED** [review]

**Comment by xorima** [comment]
can you get a changelog in @sinfomicien please?

**Comment by sinfomicien** [comment]
@Xorima : i added it under version 2.1.1 in the changelog (as 2.1.0 is already released).

**Comment by xorima** [comment]
I am not sure we should release this as a patch, it is a breaking change in that the property name has changed, I feel like we should release as 3.0.0 just so people are aware

**Review by xorima — DISMISSED** [review]

**Pull request merged**
