### PR TITLE
Prevent removal of MariaDB-compat for centos-7

### PR DESCRIPTION
**Pull request by jfwm2**
During removal of mysql-libs with yum multiple matches can be found
but chef could only use the first match: MariaDB-compat. Therefore,
because of dependencies, the removal of MariaDB-compat triggers the
one of MariaDB-server and several other packages (MariaDB-shared,
MariaDB-client, MariaDB-common, MariaDB-devel, MySQL-python).
To fix this issue we prevent the removal of mysql-libs for centos-7
and later.

### CODE REVIEW

**Comment by jfwm2** [comment]
Hello
I think there may be a problem with the The Travis CI build, because it fails even when all my changes are commented out.
Thanks

**Comment by shoekstra** [comment]
Hi!

I'm in process of sorting out some integration tests for this cookbook - once those are done we can rebase and try get this merged!

**Comment by shoekstra** [comment]
Hi @jfwm2,

The tests currently pass for CentOS 7 so is this PR still needed?

If it is can you please include more steps to try reproduce the problem faced that this PR solves?

**Comment by jfwm2** [comment]
Hello @shoekstra 
The issue still occur when mariadb is installed with a package at a version different than the default os one. Because, however, the code of the cookbook changed since the present PR was submitted, I will close it and submit a new one.
Kind regards

**Pull request closed without merging**
