### PR TITLE
scl installation recipe

### PR DESCRIPTION
**Pull request by dimsh99**
Recipe and attributes to install mariadb from Software Collections repository on centos6/7. I'm sorry for creating new PR instead of reopening #148 .

### CODE REVIEW

**Comment by shoekstra** [comment]
@dimsh99 looks good!  Can you please address the Foodcritic error:

```
FC048: Prefer Mixlib::ShellOut: /home/travis/build/sinfomicien/mariadb/providers/replication.rb:33
```

Once this has been fixed it's good to merge 👍

**Comment by dimsh99** [comment]
Should be fixed. I think mysql2_gem interface is more flexible and switching to it instead of /usr/bin/mysql execution would be beneficial for the cookbook. I have some drafts for this. Let me know if there are any objections.

**Comment by shoekstra** [comment]
Thanks!  Great contribution.

Re using mysql2_gem, agreed, it was on the consideration list for the v2.0 rewrite to use custom resources.

if you already have something then sure am interested 👍

**Comment by shoekstra** [comment]
This has been included in v1.2.0 in the Supermarket.

**Pull request merged**
