### PR TITLE
data_bag and MariaDB 10.1 support

### PR DESCRIPTION
**Pull request by engel75**
Dear sinfomicien

thank you for your great work! As we need to deploy a MariaDB 10.1 Galera Cluster I added support for it and enabled data_bag support to use encrypted passwords with the following database user:

root
debian-sys-maint
sstuser

while 'sstuser' is used by xtrabackup.

All the best,
Flo

### CODE REVIEW

**Comment by sinfomicien** [comment]
Great Job... A lot of tests are failling in kitchen for now. I will check if it's caused by your PR, or if i need to update tests. But indeed, i'm really near clicking on merge without repairing tests.

**Comment by engel75** [comment]
fixed some footcritic stuff and added /root/.my.cnf support (can be disabled via attribute)

**Comment by engel75** [comment]
finally - sorry for all those commits...

**Comment by sinfomicien** [comment]
Thx for the real good job!

**Pull request merged**
