### PR TITLE
Mariadb user problem after first run

### PR DESCRIPTION
**Pull request by jmadureira**
When checking if a database user already exists the resource is using the default state instead of the desired one. This means that any user with a `host != localhost` won't be found causing chef to try to create the user again and failing.

### CODE REVIEW

**Comment by jmadureira** [comment]
I've also included matchers for `mariadb_database` and `mariadb_user` if anyone's interested.

**Comment by stissot** [comment]
I haven't been able to reproduce the error even after multiple converges, and the `mariadb_test::resources` recipe indeed creates a user with `host != localhost`.

```
mysql -uroot -pgsql -e 'show grants for fozzie@mars'
+----------------------------------------------------------------------------------------------------------------------+
| Grants for fozzie@mars                                                                                               |
+----------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'fozzie'@'mars' IDENTIFIED BY PASSWORD '*EF112B3D562CB63EA3275593C10501B59C4A390D' REQUIRE SSL |
| GRANT SELECT, INSERT, UPDATE ON `databass`.* TO 'fozzie'@'mars'                                                      |
+----------------------------------------------------------------------------------------------------------------------+
```
The existence of a user with a matching username and host is tested in `load_current_value` before trying to create a user, so this should ensure idempotence.

I wonder if it could be a problem specific to the the version of `mysql2` gem you are using (which one?)

```
> /opt/chef/embedded/bin/gem list mysql2
*** LOCAL GEMS ***

mysql2 (0.5.0)
```

Is your mariadb server on different host than chef-client (`ctrl_host != localhost`)? This case would be difficult to test as we would have to converge 2 nodes.

Which operating system are you using? (I tested on Ubuntu 1604)

**Comment by jmadureira** [comment]
@stissot The `mariadb_user` resource works fine on the first run and indeed creates the user with the correct configuration (host attribute and everything).

The problem I found out is on the `load_current_value` itself. When logging the attributes on that method Chef always print `localhost` as the user password since it is configured to be the default one.

From what I can interpret from [the Chef documentation](https://docs.chef.io/custom_resources.html#desired-state) the `desired_state=false` tells Chef that it should assume the values defined by us and not the system (much like what you are doing with the ctrl_* properties).

For clarity the tests I ran where on:
- CentOS 7
- chef-12.16.42
- Using chef solo so it converges on the same node

**Comment by shoekstra** [comment]
Hi, thanks for creating this issue!

I'm a bit wary of accepting this one currently as I too haven't come across this issue either.  I hope to investigate more and feedback in the coming days.

**Comment by jmadureira** [comment]
Hello @shoekstra 

Of course, totally understandable. I'll see if I can add some tests to recreate this issue and update the merge request accordingly.

**Comment by sinfomicien** [comment]
Sorry to have polluted your PR, with all my commits 😢 
But you can watch my last commit to see which modification i need to correct my own bug ! ;)

**Comment by jmadureira** [comment]
Interesting catch :)
I'll need to run some tests but apparently there's an additional change to be made on my PR.

**Comment by sinfomicien** [comment]
Did you had time to test my proposal ? If you could include it, i would merge it ! Thx ;-)

**Review by sinfomicien — APPROVED** [review]

**Comment by sinfomicien** [comment]
Let me find a way to correct all tests, merge it into master, then we will verify that all tests are really good after a rebase.

**Comment by sinfomicien** [comment]
Ok, i verified the failed tests... Only because Ubuntu 16.04 repository are so slow... Tests are working locally. All good ! Many thx for your work @jmadureira 😉

**Pull request merged**
