### PR TITLE
Support Xtrabackup SST settings in my.cnf

### PR DESCRIPTION
**Pull request by rtheobald**

### CODE REVIEW

**Comment by shoekstra** [comment]
@rtheobald hi!

It would be great to get these changes merged in.  The original PR is quite old, would you be able to rebase off master or should I try do this for you?

**Comment by rtheobald** [comment]
Hi @shoekstra !

I've rebased as requested.  Let me know if you need anything else.

Cheers

**Comment by shoekstra** [comment]
Thanks!

There is some stuff I'd like to clean up before merging, would you mind ticking the **Allow edits from maintainers** check box on the right hand side below the participants please?

**Comment by rtheobald** [comment]
All yours! :)

**Comment by xorima** [comment]
Hi,

Will close as this seems orphaned, however feel free to re-open or submit a new PR

Thanks !

**Pull request closed without merging**
