### PR TITLE
Cherry-pick Ubuntu repo key fixes

### PR DESCRIPTION
**Pull request by JCotton1123**

### CODE REVIEW

**Comment by shoekstra** [comment]
Hi @JCotton1123!

Why do you want to commit changes into a version that is well behind master?

Does it not make more sense to use a more recent version of the cookbook which already has this fix?

Cheers,
Stephen

**Comment by JCotton1123** [comment]
@shoekstra we're currently using 0.3.x and I don't think its worth the time or effort to QA the upgrade especially given that we're deploying new db instances on AWS RDS. Once our non-RDS servers are gone, we can easily upgrade to the latest version for the client install.

**Comment by shoekstra** [comment]
Ah, that's a fair enough response. 😄

I was about to start adding tests but didn't as hopefully this is an edge case and not many others are using a 0.x branch.  Good luck!

**Comment by shoekstra** [comment]
0.3.4 is in the supermarket for you.

**Comment by JCotton1123** [comment]
@shoekstra Thanks! Much appreciated

**Pull request merged**
