### PR TITLE
Correct issue #193, which appeared in Debian >=9

### PR DESCRIPTION
**Pull request by sinfomicien**
And in Debian 9, dirmngr is not installed by default anymore. So i force installation (to be able to grab gpg key from keyring server)

### CODE REVIEW

**Comment by sinfomicien** [comment]
None of the failed tests come from my changes... As far as i interpret it. :(

**Comment by damacus** [comment]
Ping @shoekstra

**Comment by sinfomicien** [comment]
@damacus : perhaps you can review the PR, so that we can merge it ? @shoekstra seems busy elsewhere.

**Review by damacus — APPROVED** [review]

**Comment by sinfomicien** [comment]
Failed test, only because Ubuntu 16.04 repositioy too slow... Will merge it.

**Pull request merged**
