### PR TITLE
Add openSUSE support

### PR DESCRIPTION
**Pull request by DStape**
This does not include the server packages.

### CODE REVIEW

**Comment by shoekstra** [comment]
Great!

I've added some integration tests - let's see what happens.

**Comment by DStape** [comment]
Thanks @shoekstra, I'm in the process of fixing the failures.

**Comment by shoekstra** [comment]
Hi @DStape,

I tried to install MariaDB by hand but can't get it to start.  Installing using either OS or MariaDB repo results in a missing dependency, so I had to do `zypper in libpcre1`.  After that hit another issue or two where the process exits and eventually stopped trying.

I've pushed the work I did to add openSUSE support to the cookbook, and it would be great to support more OSes, but I'm hitting a problem with the MariaDB and openSUSE and not Chef so I'm going to stop for now. If you do get further please continue to update the PR so we can get this merged in when it's ready.

Cheers

**Comment by DStape** [comment]
Hi @shoekstra,

Interestingly, I'm not seeing that dependency issue. I've been using a fresh install of Leap 42.2 but I've also just tried with the latest opensuse docker image and not seeing it there either.

The main use case I've been working with which led me to creating this PR is installing the Ruby bindings for mysql via the 'mysql2_chef_gem' cookbook. It runs the mariadb client recipe - and the changes that currently form this PR make this work on opensuse.

I do intend on continuing to make progress on this PR, so yes please, let's keep it open.

Thanks,
David.

**Comment by xorima** [comment]
Hey, 

Thank you for the PR. We are closing due to inactivity. 
If you feel this feature should be merged in, please reopen and rebase as your contributions are always welcome.

Sous Chefs

**Pull request closed without merging**
